### ISSUE TITLE
remove some outputs content from the commond 

### ISSUE THREAD

**Issue by xiefei1024** [nervosnetwork/godwoken-doc#17]

**Comment by ashleewang888** [comment]
1. Deploy the contract part with hardhat, starting with part 5, switch to the godwoken-kicker directory instead of the godwoken-test directory.
2. Red marked parts need to be moved to output.
![image](https://user-images.githubusercontent.com/69146384/168767925-8cd81eab-6bec-49a9-a4b1-697493a6deaf.png)

**Comment by xying21** [comment]
https://github.com/nervosnetwork/godwoken-doc/pull/20/files#diff-e06bb1cdfa0a2433111d38464b489f9d69fbeaddd43165846254c52f6dc166b2
